name: my-aws-expenses-app

on:
  push:
    branches:
      - ["develop", "test"]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

  local-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Run serverless offline tests
        run: npm run start

